name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for sumitting your first issue! Admin will be in contact soon.' first issue"
        pr-message: "Congrats! Pull Requests are exiting, your code will be review and you'll recieve feedback soon!' first pull request"
